spring:
  application:
    name: ets
  datasource:
    url: jdbc:mysql://localhost:3306/employee_tracking_system?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.data.ets: DEBUG
