spring:
  application:
    name: ets
  datasource:
    url: jdbc:h2:file:./data/employee_tracking_system
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.data.ets: DEBUG
